language: python
python:
  - 3.6

before_script:
  - pip install pytest-cov codecov
  # Install go.
  - apt-get install golang-go
  # Install netorcai.
  - go get github.com/netorcai/netorcai/cmd/netorcai
  - netorcai --version

script:
  # Run tests
  - python -m pytest --cov=netorcai tests/
  # Submit coverage results to codecov.io
  - codecov
